version: "3.3"

networks:
  previewer-network:
    driver: bridge

services:
  previewer:
    image: previewer:develop
    ports:
      - '8000:8000'
    networks:
      - previewer-network
    tmpfs:
      - /tmp/cache
    command: -port ${HTTP_PORT}
