// Code generated by mockery v2.10.2. DO NOT EDIT.

package mockapp

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// GetAndResize provides a mock function with given fields: ctx, url, w, h, headers
func (_m *App) GetAndResize(ctx context.Context, url string, w int, h int, headers http.Header) ([]byte, error) {
	ret := _m.Called(ctx, url, w, h, headers)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, http.Header) []byte); ok {
		r0 = rf(ctx, url, w, h, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, http.Header) error); ok {
		r1 = rf(ctx, url, w, h, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
