// Code generated by mockery v2.10.2. DO NOT EDIT.

package mockfilesystem

import mock "github.com/stretchr/testify/mock"

// Filesystem is an autogenerated mock type for the Filesystem type
type Filesystem struct {
	mock.Mock
}

// ReadFile provides a mock function with given fields: name
func (_m *Filesystem) ReadFile(name string) ([]byte, error) {
	ret := _m.Called(name)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFile provides a mock function with given fields: name
func (_m *Filesystem) RemoveFile(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteFile provides a mock function with given fields: name, content
func (_m *Filesystem) WriteFile(name string, content []byte) error {
	ret := _m.Called(name, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(name, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
