name: Code Autotests

on:
  pull_request:

env:
  GO111MODULE: "on"

jobs:
  test_with_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.9

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint
        run: make lint

      - name: Build
        run: make build

      - name: Test
        run: make test
